using Neba.Api.Features.Tournaments.Domain;

namespace Neba.Api.Features.News.GetArticle;

/// <summary>
/// Represents the details of a news article, including its title, content, publication date, header image information, and any associated attachments. This DTO (Data Transfer Object) is used to transfer article data from the server to the client in a structured format. The Slug is included for SEO-friendly URLs, while the HeaderImageContainer, HeaderImagePath, and HeaderImageUrl provide information about the article's header image if one is associated with the article. The Attachments property contains a collection of ArticleAttachmentDto objects representing any files or images attached to the article. This DTO is designed to provide all necessary information for displaying a news article on the client side while maintaining a clear separation of concerns between the domain model and the data transfer layer.
/// </summary>
public sealed record ArticleDetailDto
{
    /// <summary>
    /// The slug is a URL-friendly version of the article title, typically generated by converting the title to lowercase, replacing spaces with hyphens, and removing special characters. This is used in the article's URL to improve SEO and make the URL more readable. The slug should be unique across all articles to avoid URL conflicts. It is a required field and is often generated automatically based on the title when creating or updating an article.
    /// </summary>
    public required string Slug { get; init; }

    /// <summary>
    /// The title of the news article. This is a required field and should be a concise summary of the article's content. The title is used for display purposes on the website and should be unique enough to distinguish it from other articles. It is also used in the generation of the article's slug for SEO-friendly URLs.
    /// </summary>
    public required string Title { get; init; }

    /// <summary>
    /// The main content of the news article. This is a required field and contains the full text of the article, including any formatting, images, or other media that may be included in the article body. The content is typically stored in a rich text format (e.g., HTML) to allow for proper rendering on the website. It should provide all necessary information about the news event being reported and can include links to related articles or external sources for additional context.
    /// </summary>
    public required string Content { get; init; }

    /// <summary>
    /// The name of the storage container where the header image is stored. This is used to locate the header image in the storage system. This field is optional and may be null if no header image is associated with the article.
    /// </summary>
    public string? HeaderImageContainer { get; init; }

    /// <summary>
    /// The path to the header image within the storage container. This is used in conjunction with the container name to access the header image. This field is optional and may be null if no header image is associated with the article.
    /// </summary>
    public string? HeaderImagePath { get; init; }

    /// <summary>
    /// The URL to access the header image. This may be null if no header image is associated with the article or if the URL is not provided. If a header image is associated with the article, this URL can be used to display the header image on the client side.
    /// </summary>
    public Uri? HeaderImageUrl { get; init; }

    /// <summary>
    /// The date and time when the news article was published, stored in UTC. This is a required field for all articles and is used to determine the chronological order of articles on the website. The PublishDateUtc should be set to the current date and time when an article's PublicationStatus is changed to "Published". This allows for accurate sorting and display of articles based on their publication date, and it also provides important information for users about when the news event being reported occurred.
    /// </summary>
    public required DateTimeOffset PublishDateUtc { get; init; }

    /// <summary>
    /// A list of attachments associated with the news article. Attachments can include images, documents, or any other file types that are relevant to the article's content. Each attachment is represented by an ArticleAttachmentDto object, which contains information about the attachment such as its display name, reference to the stored file, and URL for accessing the attachment. This list allows for multiple attachments to be associated with a single article, providing additional context and resources for readers. The attachments are exposed as a read-only collection to ensure that they cannot be modified directly from external code, maintaining the integrity of the article's data.
    /// </summary>
    public IReadOnlyCollection<ArticleAttachmentDto> Attachments { get; init; } = [];

    /// <summary>
    /// An optional reference to a tournament associated with the news article. This is used to link news articles to specific tournaments, allowing for better organization and navigation on the website. If an article is related to a particular tournament (e.g., a tournament announcement, results summary, or player profile), the TournamentId can be set to the ID of that tournament. This allows users to easily find all news articles related to a specific tournament and provides additional context for the news event being reported. If an article is not related to any tournament, this field can be left null.
    /// </summary>
    public TournamentId? TournamentId { get; init; }
}