using StronglyTypedIds;

namespace Neba.Domain.HallOfFame;

/// <summary>
/// Represents a strongly-typed identifier for Hall of Fame entries.
/// </summary>
/// <remarks>
/// This is a ULID-based strongly-typed id generated by the
/// <c>StronglyTypedIds</c> source generator using the format "ulid-full".
/// Use this type instead of raw strings to ensure type-safety across the domain.
/// </remarks>
[StronglyTypedId("ulid-full")]
public readonly partial struct HallOfFameId
{
    /// <summary>Gets the underlying <see cref="Ulid"/> value.</summary>
    public Ulid Value { get; }
    private HallOfFameId(Ulid value)
        => Value = value;

    /// <summary>Creates a new <see cref="HallOfFameId"/> with a randomly generated ULID value.</summary>
    public static HallOfFameId New() => new(Ulid.NewUlid());
}