
using Neba.Domain.Bowlers;

namespace Neba.Domain.HallOfFame;

/// <summary>
/// Represents an induction into the Hall of Fame.
/// </summary>
/// <remarks>
/// This entity is the domain root for a Hall of Fame entry and
/// uses a strongly-typed <see cref="HallOfFameId"/> (ULID) as its identifier.
/// Keep business logic for induction events and rules on this entity.
/// </remarks>
public sealed class HallOfFameInduction
    : AggregateRoot
{
    /// <summary>
    /// The unique identifier for this Hall of Fame induction.
     /// This is a strongly-typed ULID-based id generated by the
     /// <c>StronglyTypedIds</c> source generator using the format "ulid-full".
     /// Use this type instead of raw strings to ensure type-safety across the domain.
    /// </summary>
    public HallOfFameId Id { get; init; }

    /// <summary>
    /// The year the induction took place.
    /// </summary>
    public int Year { get; init; }

    /// <summary>
    /// The identifier of the bowler associated with this induction.
    /// This is a reference to the <see cref="Bowler"/> entity in the Bowlers bounded context.
    /// Use this ID for external references instead of the navigation property to avoid cross-context coupling.
    /// </summary>
    public BowlerId BowlerId { get; init; }

    /// <summary>
    /// The bowler associated with this induction.
    /// This is a reference to the <see cref="Bowler"/> entity in the Bowlers bounded context.
    /// This property is internal to prevent cross-context references from outside the domain layer.
    /// Use the Bowler's ID or other value objects for external references instead.
    /// Keep this as a navigation property for internal use within the Hall of Fame context.
    /// </summary>
    internal Bowler Bowler { get; init; } = null!;

    /// <summary>
    /// The categories associated with this induction.
    /// </summary>
    public IReadOnlyCollection<HallOfFameCategory> Categories { get; init; } = [];
}
