using StronglyTypedIds;

namespace Neba.Domain.HallOfFame;

/// <summary>
/// Represents a strongly-typed identifier for Hall of Fame entries.
/// </summary>
/// <remarks>
/// This is a ULID-based strongly-typed id generated by the
/// <c>StronglyTypedIds</c> source generator using the format "ulid-full".
/// Use this type instead of raw strings to ensure type-safety across the domain.
/// </remarks>
[StronglyTypedId("ulid-full")]
public readonly partial struct HallOfFameId;