using ErrorOr;

using Neba.Api.Domain;
using Neba.Api.Features.Storage.Domain;
using Neba.Api.Features.Tournaments.Domain;

namespace Neba.Api.Features.News.Domain;

/// <summary>
/// Represents a news article on the website. This class contains all relevant information about a news article, including its title, content, publication status, and associated tournament (if any). The ArticleId is a strongly-typed identifier to ensure type safety when working with article IDs throughout the codebase. The PublicationStatus is implemented as a SmartEnum to allow for easy expansion of possible statuses in the future without breaking existing code or database schema.
/// </summary>
public sealed class Article
    : AggregateRoot
{
    /// <summary>
    /// Unique identifier for the news article. This is a strongly-typed ID to ensure type safety when working with article IDs throughout the codebase. The underlying value is a ULID, which provides both uniqueness and chronological sorting capabilities. This ID is required for all articles and is used as the primary key in the database.
    /// </summary>
    public required ArticleId Id { get; init; }

    /// <summary>
    /// The title of the news article. This is a required field and should be a concise summary of the article's content. The title is used for display purposes on the website and should be unique enough to distinguish it from other articles. It is also used in the generation of the article's slug for SEO-friendly URLs.
    /// </summary>
    public required string Title { get; init; }

    /// <summary>
    /// The slug is a URL-friendly version of the article title, typically generated by converting the title to lowercase, replacing spaces with hyphens, and removing special characters. This is used in the article's URL to improve SEO and make the URL more readable. The slug should be unique across all articles to avoid URL conflicts. It is a required field and is often generated automatically based on the title when creating or updating an article.
    /// </summary>
    public required string Slug { get; init; }

    /// <summary>
    /// The main content of the news article. This is a required field and contains the full text of the article, including any formatting, images, or other media that may be included in the article body. The content is typically stored in a rich text format (e.g., HTML) to allow for proper rendering on the website. It should provide all necessary information about the news event being reported and can include links to related articles or external sources for additional context.
    /// </summary>
    public required string Content { get; init; }

    /// <summary>
    /// The publication status of the news article, represented as a SmartEnum. This indicates whether the article is currently in draft status (not yet published) or has been published and is visible on the website. The PublicationStatus is stored as an integer in the database (0 for Draft, 1 for Published) to allow for efficient storage and comparison. This field is required for all articles and is used to determine whether an article should be displayed on the website or not. Future statuses (e.g., "Archived", "Scheduled") can be added to the PublicationStatus enum without breaking existing code or database schema.
    /// </summary>
    public required PublicationStatus PublicationStatus { get; init; }

    /// <summary>
    /// The date and time when the news article was published, stored in UTC. This is a required field for all articles and is used to determine the chronological order of articles on the website. The PublishDateUtc should be set to the current date and time when an article's PublicationStatus is changed to "Published". This allows for accurate sorting and display of articles based on their publication date, and it also provides important information for users about when the news event being reported occurred.
    /// </summary>
    public required DateTimeOffset PublishDateUtc { get; init; }

    /// <summary>
    /// An optional header image associated with the news article. This is stored as a reference to a file in the storage system (e.g., a URL or file ID) and can be used to enhance the visual appeal of the article when displayed on the website. The header image is not required, but if provided, it should be relevant to the content of the article and meet any size or format requirements specified by the website's design guidelines. The presence of a header image can help attract readers' attention and provide additional context for the news event being reported.
    /// </summary>
    public StoredFile? HeaderImage { get; init; }

    /// <summary>
    /// An optional reference to a tournament associated with the news article. This is used to link news articles to specific tournaments, allowing for better organization and navigation on the website. If an article is related to a particular tournament (e.g., a tournament announcement, results summary, or player profile), the TournamentId can be set to the ID of that tournament. This allows users to easily find all news articles related to a specific tournament and provides additional context for the news event being reported. If an article is not related to any tournament, this field can be left null.
    /// </summary>
    public TournamentId? TournamentId { get; init; }

    internal Tournament? Tournament { get; init; }

    private readonly List<ArticleAttachment> _attachments = [];

    /// <summary>
    /// A list of attachments associated with the news article. Attachments can include images, documents, or any other file types that are relevant to the article's content. Each attachment is represented by an ArticleAttachment object, which contains information about the attachment such as its unique identifier, display name, reference to the stored file, and whether it should be displayed inline with the article content. This list allows for multiple attachments to be associated with a single article, providing additional context and resources for readers. The attachments are stored in a private list to allow for controlled modification (e.g., adding or removing attachments) while exposing a read-only collection to external code.
    /// </summary>
    public IReadOnlyList<ArticleAttachment> Attachments
        => _attachments.AsReadOnly();

    /// <summary>
    /// Adds an attachment to the article. Returns a validation error if the display name is empty.
    /// </summary>
    public ErrorOr<Success> AddAttachment(string displayName, StoredFile file, bool isInline)
    {
        var attachment = ArticleAttachment.Create(displayName, file, isInline);

        if (attachment.IsError)
        {
            return attachment.Errors;
        }

        _attachments.Add(attachment.Value);

        return Result.Success;
    }
}