// <auto-generated>

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Neba.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class BowlerSeasonStats_Init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "bowler_season_stats",
                schema: "app",
                columns: table => new
                {
                    // Keys
                    season_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    // Classification
                    is_member = table.Column<bool>(type: "boolean", nullable: false),
                    is_rookie = table.Column<bool>(type: "boolean", nullable: false),
                    is_senior = table.Column<bool>(type: "boolean", nullable: false),
                    is_super_senior = table.Column<bool>(type: "boolean", nullable: false),
                    is_woman = table.Column<bool>(type: "boolean", nullable: false),
                    is_youth = table.Column<bool>(type: "boolean", nullable: false),
                    // Participation
                    tournaments = table.Column<int>(type: "integer", nullable: false),
                    total_tournaments = table.Column<int>(type: "integer", nullable: false),
                    entries = table.Column<int>(type: "integer", nullable: false),
                    total_entries = table.Column<int>(type: "integer", nullable: false),
                    cashes = table.Column<int>(type: "integer", nullable: false),
                    finals = table.Column<int>(type: "integer", nullable: false),
                    // Performance
                    total_games = table.Column<int>(type: "integer", nullable: false),
                    total_pinfall = table.Column<int>(type: "integer", nullable: false),
                    field_average = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: false),
                    qualifying_high_game = table.Column<int>(type: "integer", nullable: false),
                    high_block = table.Column<int>(type: "integer", nullable: false),
                    high_finish = table.Column<int>(type: "integer", nullable: true),
                    average_finish = table.Column<decimal>(type: "numeric(3,1)", precision: 3, scale: 1, nullable: true),
                    // Match play
                    match_play_wins = table.Column<int>(type: "integer", nullable: false),
                    match_play_losses = table.Column<int>(type: "integer", nullable: false),
                    match_play_games = table.Column<int>(type: "integer", nullable: false),
                    match_play_pinfall = table.Column<int>(type: "integer", nullable: false),
                    match_play_high_game = table.Column<int>(type: "integer", nullable: false),
                    // Points
                    bowler_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    senior_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    super_senior_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    woman_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    youth_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    // Financials
                    tournament_winnings = table.Column<decimal>(type: "numeric(7,2)", precision: 7, scale: 2, nullable: false),
                    cup_earnings = table.Column<decimal>(type: "numeric(7,2)", precision: 7, scale: 2, nullable: false),
                    credits = table.Column<decimal>(type: "numeric(7,2)", precision: 7, scale: 2, nullable: false),
                    // Audit
                    last_updated_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowler_season_stats", x => new { x.season_id, x.bowler_id });
                    table.ForeignKey(
                        name: "fk_bowler_season_stats_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_bowler_season_stats_seasons_season_id",
                        column: x => x.season_id,
                        principalSchema: "app",
                        principalTable: "seasons",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowler_season_stats_bowler_id",
                schema: "app",
                table: "bowler_season_stats",
                column: "bowler_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "bowler_season_stats",
                schema: "app");
        }
    }
}
