// <auto-generated>

using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Bowlers_Init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "bowlers",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    first_name = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: false),
                    last_name = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    middle_name = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: true),
                    suffix = table.Column<string>(type: "character varying(7)", maxLength: 7, nullable: true),
                    nickname = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: true),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    legacy_id = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowlers", x => x.id);
                    table.UniqueConstraint("ak_bowlers_domain_id", x => x.domain_id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_legacy_id",
                schema: "app",
                table: "bowlers",
                column: "legacy_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_name_last_name_name_first_name",
                schema: "app",
                table: "bowlers",
                columns: new[] { "last_name", "first_name" });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_website_id",
                schema: "app",
                table: "bowlers",
                column: "website_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "bowlers",
                schema: "app");
        }
    }
}
