// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neba.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311182437_HallOfFameInduction_Init")]
    partial class HallOfFameInduction_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.HasKey("db_id")
                        .HasName("pk_bowlers");

                    b.HasAlternateKey("Id")
                        .HasName("ak_bowlers_domain_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowlers_legacy_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("LegacyId"), true);

                    b.HasIndex("WebsiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowlers_website_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("WebsiteId"), true);

                    b.ToTable("bowlers", "app");
                });

            modelBuilder.Entity("Neba.Domain.BowlingCenters.BowlingCenter", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("certification_number");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Neba.Domain.BowlingCenters.BowlingCenter.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("country")
                                .IsFixedLength();

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("state")
                                .IsFixedLength();

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");

                            b1.Property<string>("Unit")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Coordinates", "Neba.Domain.BowlingCenters.BowlingCenter.Address#Address.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmailAddress", "Neba.Domain.BowlingCenters.BowlingCenter.EmailAddress#EmailAddress", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email_address");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_bowling_centers");

                    b.HasAlternateKey("CertificationNumber")
                        .HasName("ak_bowling_centers_certification_number");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowling_centers_legacy_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("LegacyId"), true);

                    b.HasIndex("WebsiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowling_centers_website_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("WebsiteId"), true);

                    b.ToTable("bowling_centers", "app");
                });

            modelBuilder.Entity("Neba.Domain.HallOfFame.HallOfFameInduction", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("BowlerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("bowler_id")
                        .IsFixedLength();

                    b.Property<int>("Categories")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("induction_year");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Photo", "Neba.Domain.HallOfFame.HallOfFameInduction.Photo#StoredFile", b1 =>
                        {
                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("character varying(63)")
                                .HasColumnName("photo_container");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("photo_content_type");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(1023)
                                .HasColumnType("character varying(1023)")
                                .HasColumnName("photo_file_path");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("photo_size_in_bytes");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_hall_of_fame_inductions");

                    b.HasAlternateKey("Id")
                        .HasName("ak_hall_of_fame_inductions_domain_id");

                    b.HasAlternateKey("Year", "BowlerId")
                        .HasName("ak_hall_of_fame_inductions_induction_year_bowler_id");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_hall_of_fame_inductions_bowler_id");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_hall_of_fame_inductions_induction_year");

                    b.ToTable("hall_of_fame_inductions", "app");
                });

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.OwnsOne("Neba.Domain.Bowlers.Name", "Name", b1 =>
                        {
                            b1.Property<int>("Bowlerdb_id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(31)
                                .HasColumnType("character varying(31)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("character varying(63)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(31)
                                .HasColumnType("character varying(31)")
                                .HasColumnName("middle_name");

                            b1.Property<string>("Nickname")
                                .HasMaxLength(31)
                                .HasColumnType("character varying(31)")
                                .HasColumnName("nickname");

                            b1.Property<string>("Suffix")
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("suffix");

                            b1.HasKey("Bowlerdb_id");

                            b1.HasIndex("LastName", "FirstName")
                                .HasDatabaseName("ix_bowlers_name_last_name_name_first_name");

                            b1.ToTable("bowlers", "app");

                            b1.WithOwner()
                                .HasForeignKey("Bowlerdb_id")
                                .HasConstraintName("fk_bowlers_bowlers_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Neba.Domain.BowlingCenters.BowlingCenter", b =>
                {
                    b.OwnsOne("Neba.Domain.BowlingCenters.LaneConfiguration", "Lanes", b1 =>
                        {
                            b1.Property<int>("BowlingCenterdb_id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.HasKey("BowlingCenterdb_id");

                            b1.ToTable("bowling_centers", "app");

                            b1.WithOwner()
                                .HasForeignKey("BowlingCenterdb_id")
                                .HasConstraintName("fk_bowling_centers_bowling_centers_id");

                            b1.OwnsMany("Neba.Domain.BowlingCenters.LaneRange", "Ranges", b2 =>
                                {
                                    b2.Property<int>("bowling_center_id")
                                        .HasColumnType("integer")
                                        .HasColumnName("bowling_center_id");

                                    b2.Property<int>("StartLane")
                                        .HasColumnType("integer")
                                        .HasColumnName("start_lane");

                                    b2.Property<int>("EndLane")
                                        .HasColumnType("integer")
                                        .HasColumnName("end_lane");

                                    b2.Property<string>("PinFallType")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character(2)")
                                        .HasColumnName("pin_fall_type")
                                        .IsFixedLength();

                                    b2.HasKey("bowling_center_id", "StartLane")
                                        .HasName("pk_bowling_center_lanes");

                                    b2.ToTable("bowling_center_lanes", "app");

                                    b2.WithOwner()
                                        .HasForeignKey("bowling_center_id")
                                        .HasConstraintName("fk_bowling_center_lanes_bowling_centers_bowling_center_id");
                                });

                            b1.Navigation("Ranges");
                        });

                    b.OwnsMany("Neba.Domain.Contact.PhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<int>("bowling_center_id")
                                .HasColumnType("integer")
                                .HasColumnName("bowling_center_id");

                            b1.Property<string>("Type")
                                .HasMaxLength(1)
                                .HasColumnType("character(1)")
                                .HasColumnName("phone_type")
                                .IsFixedLength();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("phone_country_code");

                            b1.Property<string>("Extension")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_extension");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("bowling_center_id", "Type")
                                .HasName("pk_bowling_center_phone_numbers");

                            b1.ToTable("bowling_center_phone_numbers", "app");

                            b1.WithOwner()
                                .HasForeignKey("bowling_center_id")
                                .HasConstraintName("fk_bowling_center_phone_numbers_bowling_centers_bowling_center");
                        });

                    b.Navigation("Lanes")
                        .IsRequired();

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("Neba.Domain.HallOfFame.HallOfFameInduction", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hall_of_fame_inductions_bowlers_bowler_id");

                    b.Navigation("Bowler");
                });
#pragma warning restore 612, 618
        }
    }
}
