// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Api.Database.Migrations
{
    /// <inheritdoc />
    public partial class SquadScore_Init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "squad_scores",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    squad_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    game_number = table.Column<short>(type: "smallint", nullable: false),
                    score = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_squad_scores", x => x.id);
                    table.UniqueConstraint("ak_squad_scores_domain_id", x => x.domain_id);
                    table.UniqueConstraint("ak_squad_scores_squad_id_bowler_id_game_number", x => new { x.squad_id, x.bowler_id, x.game_number });
                    table.ForeignKey(
                        name: "fk_squad_scores_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_squad_scores_squads_squad_id",
                        column: x => x.squad_id,
                        principalSchema: "app",
                        principalTable: "squads",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_squad_scores_bowler_id",
                schema: "app",
                table: "squad_scores",
                column: "bowler_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "squad_scores",
                schema: "app");
        }
    }
}
