// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Api.Database.Migrations
{
    /// <inheritdoc />
    public partial class App_Init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "app");

            migrationBuilder.EnsureSchema(
                name: "staging");

            migrationBuilder.EnsureSchema(
                name: "historical");

            migrationBuilder.CreateTable(
                name: "bowlers",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    first_name = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: false),
                    middle_name = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: true),
                    last_name = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    suffix = table.Column<string>(type: "character varying(7)", maxLength: 7, nullable: true),
                    nickname = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: true),
                    gender = table.Column<string>(type: "character varying(1)", maxLength: 1, nullable: true),
                    date_of_birth = table.Column<DateOnly>(type: "date", nullable: true),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    legacy_id = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowlers", x => x.id);
                    table.UniqueConstraint("ak_bowlers_domain_id", x => x.domain_id);
                });

            migrationBuilder.CreateTable(
                name: "bowling_centers",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    certification_number = table.Column<string>(type: "character varying(6)", maxLength: 6, nullable: false),
                    name = table.Column<string>(type: "character varying(127)", maxLength: 127, nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    website = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    website_id = table.Column<int>(type: "integer", nullable: true),
                    legacy_id = table.Column<int>(type: "integer", nullable: true),
                    street = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    unit = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    city = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    state = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: false),
                    country = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: false),
                    postal_code = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    latitude = table.Column<double>(type: "double precision", nullable: false),
                    longitude = table.Column<double>(type: "double precision", nullable: false),
                    email_address = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowling_centers", x => x.id);
                    table.UniqueConstraint("ak_bowling_centers_certification_number", x => x.certification_number);
                });

            migrationBuilder.CreateTable(
                name: "oil_patterns",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    name = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    length = table.Column<int>(type: "integer", nullable: false),
                    volume = table.Column<decimal>(type: "numeric(5,3)", precision: 5, scale: 3, nullable: false),
                    left_ratio = table.Column<decimal>(type: "numeric(4,2)", precision: 4, scale: 2, nullable: false),
                    right_ratio = table.Column<decimal>(type: "numeric(4,2)", precision: 4, scale: 2, nullable: false),
                    kegel_id = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_oil_patterns", x => x.id);
                    table.UniqueConstraint("ak_oil_patterns_domain_id", x => x.domain_id);
                });

            migrationBuilder.CreateTable(
                name: "pending_uploads",
                schema: "staging",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    container = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    path = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                    uploaded_at_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_pending_uploads", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "seasons",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    description = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: false),
                    start_date = table.Column<DateOnly>(type: "date", nullable: false),
                    end_date = table.Column<DateOnly>(type: "date", nullable: false),
                    complete = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_seasons", x => x.id);
                    table.UniqueConstraint("ak_seasons_domain_id", x => x.domain_id);
                });

            migrationBuilder.CreateTable(
                name: "side_cuts",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    name = table.Column<string>(type: "character varying(31)", maxLength: 31, nullable: false),
                    color_indicator = table.Column<int>(type: "integer", nullable: false),
                    logical_operator = table.Column<string>(type: "character varying(7)", maxLength: 7, nullable: false),
                    active = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_side_cuts", x => x.id);
                    table.UniqueConstraint("ak_side_cuts_domain_id", x => x.domain_id);
                });

            migrationBuilder.CreateTable(
                name: "sponsors",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    slug = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    name = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    current_sponsor = table.Column<bool>(type: "boolean", nullable: false),
                    priority = table.Column<int>(type: "integer", nullable: false),
                    tier = table.Column<int>(type: "integer", nullable: false),
                    category = table.Column<int>(type: "integer", nullable: false),
                    tag_phrase = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    description = table.Column<string>(type: "character varying(1023)", maxLength: 1023, nullable: true),
                    live_read_text = table.Column<string>(type: "character varying(2047)", maxLength: 2047, nullable: true),
                    promotional_notes = table.Column<string>(type: "character varying(4095)", maxLength: 4095, nullable: true),
                    website_url = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    facebook_url = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    instagram_url = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    business_street = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    business_unit = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    business_city = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    business_region = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: true),
                    business_country = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: true),
                    business_postal_code = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true),
                    business_latitude = table.Column<double>(type: "double precision", nullable: true),
                    business_longitude = table.Column<double>(type: "double precision", nullable: true),
                    business_email_address = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    contact_name = table.Column<string>(type: "character varying(127)", maxLength: 127, nullable: true),
                    contact_phone_type = table.Column<string>(type: "character(1)", fixedLength: true, maxLength: 1, nullable: true),
                    contact_phone_country_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: true),
                    contact_phone_number = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: true),
                    contact_phone_extension = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true),
                    contact_email_address = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    logo_container = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: true),
                    logo_file_path = table.Column<string>(type: "character varying(1023)", maxLength: 1023, nullable: true),
                    logo_content_type = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    logo_size_in_bytes = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_sponsors", x => x.id);
                    table.UniqueConstraint("ak_sponsors_domain_id", x => x.domain_id);
                    table.UniqueConstraint("ak_sponsors_slug", x => x.slug);
                });

            migrationBuilder.CreateTable(
                name: "hall_of_fame_inductions",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    induction_year = table.Column<int>(type: "integer", nullable: false),
                    category = table.Column<int>(type: "integer", nullable: false),
                    photo_container = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: true),
                    photo_file_path = table.Column<string>(type: "character varying(1023)", maxLength: 1023, nullable: true),
                    photo_content_type = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    photo_size_in_bytes = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_hall_of_fame_inductions", x => x.id);
                    table.UniqueConstraint("ak_hall_of_fame_inductions_domain_id", x => x.domain_id);
                    table.UniqueConstraint("ak_hall_of_fame_inductions_induction_year_bowler_id", x => new { x.induction_year, x.bowler_id });
                    table.ForeignKey(
                        name: "fk_hall_of_fame_inductions_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "bowling_center_lanes",
                schema: "app",
                columns: table => new
                {
                    bowling_center_id = table.Column<int>(type: "integer", nullable: false),
                    start_lane = table.Column<int>(type: "integer", nullable: false),
                    end_lane = table.Column<int>(type: "integer", nullable: false),
                    pin_fall_type = table.Column<string>(type: "character(2)", fixedLength: true, maxLength: 2, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowling_center_lanes", x => new { x.bowling_center_id, x.start_lane });
                    table.ForeignKey(
                        name: "fk_bowling_center_lanes_bowling_centers_bowling_center_id",
                        column: x => x.bowling_center_id,
                        principalSchema: "app",
                        principalTable: "bowling_centers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "bowling_center_phone_numbers",
                schema: "app",
                columns: table => new
                {
                    bowling_center_id = table.Column<int>(type: "integer", nullable: false),
                    phone_type = table.Column<string>(type: "character(1)", fixedLength: true, maxLength: 1, nullable: false),
                    phone_country_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    phone_number = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: false),
                    phone_extension = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowling_center_phone_numbers", x => new { x.bowling_center_id, x.phone_type });
                    table.ForeignKey(
                        name: "fk_bowling_center_phone_numbers_bowling_centers_bowling_center",
                        column: x => x.bowling_center_id,
                        principalSchema: "app",
                        principalTable: "bowling_centers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "bowler_of_the_year_awards",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    season_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    category = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowler_of_the_year_awards", x => x.id);
                    table.UniqueConstraint("ak_bowler_of_the_year_awards_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_bowler_of_the_year_awards_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_bowler_of_the_year_awards_seasons_season_id",
                        column: x => x.season_id,
                        principalSchema: "app",
                        principalTable: "seasons",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "bowler_season_stats",
                schema: "app",
                columns: table => new
                {
                    season_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    is_member = table.Column<bool>(type: "boolean", nullable: false),
                    is_rookie = table.Column<bool>(type: "boolean", nullable: false),
                    is_senior = table.Column<bool>(type: "boolean", nullable: false),
                    is_super_senior = table.Column<bool>(type: "boolean", nullable: false),
                    is_woman = table.Column<bool>(type: "boolean", nullable: false),
                    is_youth = table.Column<bool>(type: "boolean", nullable: false),
                    tournaments = table.Column<int>(type: "integer", nullable: false),
                    total_tournaments = table.Column<int>(type: "integer", nullable: false),
                    entries = table.Column<int>(type: "integer", nullable: false),
                    total_entries = table.Column<int>(type: "integer", nullable: false),
                    cashes = table.Column<int>(type: "integer", nullable: false),
                    finals = table.Column<int>(type: "integer", nullable: false),
                    total_games = table.Column<int>(type: "integer", nullable: false),
                    total_pinfall = table.Column<int>(type: "integer", nullable: false),
                    field_average = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: false),
                    qualifying_high_game = table.Column<int>(type: "integer", nullable: false),
                    high_block = table.Column<int>(type: "integer", nullable: false),
                    high_finish = table.Column<int>(type: "integer", nullable: true),
                    average_finish = table.Column<decimal>(type: "numeric(3,1)", precision: 3, scale: 1, nullable: true),
                    match_play_wins = table.Column<int>(type: "integer", nullable: false),
                    match_play_losses = table.Column<int>(type: "integer", nullable: false),
                    match_play_games = table.Column<int>(type: "integer", nullable: false),
                    match_play_pinfall = table.Column<int>(type: "integer", nullable: false),
                    match_play_high_game = table.Column<int>(type: "integer", nullable: false),
                    bowler_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    senior_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    super_senior_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    woman_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    youth_of_the_year_points = table.Column<int>(type: "integer", nullable: false),
                    tournament_winnings = table.Column<decimal>(type: "numeric(7,2)", precision: 7, scale: 2, nullable: false),
                    cup_earnings = table.Column<decimal>(type: "numeric(7,2)", precision: 7, scale: 2, nullable: false),
                    credits = table.Column<decimal>(type: "numeric(7,2)", precision: 7, scale: 2, nullable: false),
                    last_updated_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_bowler_season_stats", x => new { x.season_id, x.bowler_id });
                    table.ForeignKey(
                        name: "fk_bowler_season_stats_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_bowler_season_stats_seasons_season_id",
                        column: x => x.season_id,
                        principalSchema: "app",
                        principalTable: "seasons",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "high_average_awards",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    season_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    average = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: false),
                    total_games = table.Column<int>(type: "integer", nullable: true),
                    tournaments_participated = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_high_average_awards", x => x.id);
                    table.UniqueConstraint("ak_high_average_awards_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_high_average_awards_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_high_average_awards_seasons_season_id",
                        column: x => x.season_id,
                        principalSchema: "app",
                        principalTable: "seasons",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "high_block_awards",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    season_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    score = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_high_block_awards", x => x.id);
                    table.UniqueConstraint("ak_high_block_awards_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_high_block_awards_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_high_block_awards_seasons_season_id",
                        column: x => x.season_id,
                        principalSchema: "app",
                        principalTable: "seasons",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournaments",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    name = table.Column<string>(type: "character varying(127)", maxLength: 127, nullable: false),
                    tournament_type = table.Column<int>(type: "integer", nullable: false),
                    start_date = table.Column<DateOnly>(type: "date", nullable: false),
                    end_date = table.Column<DateOnly>(type: "date", nullable: false),
                    stats_eligible = table.Column<bool>(type: "boolean", nullable: false),
                    complete = table.Column<bool>(type: "boolean", nullable: false),
                    season_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    bowling_center_id = table.Column<string>(type: "character varying(6)", maxLength: 6, nullable: true),
                    entry_fee = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: false),
                    neba_added_money = table.Column<decimal>(type: "numeric(9,2)", precision: 9, scale: 2, nullable: false),
                    external_registration_url = table.Column<string>(type: "character varying(511)", maxLength: 511, nullable: true),
                    pattern_length_category = table.Column<int>(type: "integer", nullable: true),
                    pattern_ratio_category = table.Column<int>(type: "integer", nullable: true),
                    oil_pattern_reveal_date_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    logo_container = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: true),
                    logo_file_path = table.Column<string>(type: "character varying(1023)", maxLength: 1023, nullable: true),
                    logo_content_type = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    logo_size_in_bytes = table.Column<long>(type: "bigint", nullable: true),
                    legacy_id = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tournaments", x => x.id);
                    table.UniqueConstraint("ak_tournaments_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_tournaments_bowling_centers_bowling_center_id",
                        column: x => x.bowling_center_id,
                        principalSchema: "app",
                        principalTable: "bowling_centers",
                        principalColumn: "certification_number");
                    table.ForeignKey(
                        name: "fk_tournaments_seasons_season_id",
                        column: x => x.season_id,
                        principalSchema: "app",
                        principalTable: "seasons",
                        principalColumn: "domain_id");
                });

            migrationBuilder.CreateTable(
                name: "side_cut_criteria_groups",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    side_cut_id = table.Column<int>(type: "integer", nullable: false),
                    logical_operator = table.Column<string>(type: "character varying(7)", maxLength: 7, nullable: false),
                    sort_order = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_side_cut_criteria_groups", x => x.id);
                    table.UniqueConstraint("ak_side_cut_criteria_groups_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_side_cut_criteria_groups_side_cuts_side_cut_id",
                        column: x => x.side_cut_id,
                        principalSchema: "app",
                        principalTable: "side_cuts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "sponsor_phone_numbers",
                schema: "app",
                columns: table => new
                {
                    sponsor_id = table.Column<int>(type: "integer", nullable: false),
                    phone_type = table.Column<string>(type: "character(1)", fixedLength: true, maxLength: 1, nullable: false),
                    phone_country_code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    phone_number = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: false),
                    phone_extension = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_sponsor_phone_numbers", x => new { x.sponsor_id, x.phone_type });
                    table.ForeignKey(
                        name: "fk_sponsor_phone_numbers_sponsors_sponsor_id",
                        column: x => x.sponsor_id,
                        principalSchema: "app",
                        principalTable: "sponsors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "articles",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    title = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    slug = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    content = table.Column<string>(type: "text", nullable: false),
                    publication_status = table.Column<int>(type: "integer", nullable: false),
                    publish_date_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    tournament_id = table.Column<string>(type: "character(26)", nullable: true),
                    header_image_container = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: true),
                    header_image_file_path = table.Column<string>(type: "character varying(1023)", maxLength: 1023, nullable: true),
                    header_image_content_type = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    header_image_size_in_bytes = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_articles", x => x.id);
                    table.UniqueConstraint("ak_articles_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_articles_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "domain_id");
                });

            migrationBuilder.CreateTable(
                name: "squads",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    bowling_date_time_utc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    max_entries = table.Column<int>(type: "integer", nullable: true),
                    legacy_id = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_squads", x => x.id);
                    table.UniqueConstraint("ak_squads_domain_id", x => x.domain_id);
                    table.ForeignKey(
                        name: "fk_squads_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournament_champions",
                schema: "historical",
                columns: table => new
                {
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tournament_champions", x => new { x.tournament_id, x.bowler_id });
                    table.ForeignKey(
                        name: "fk_tournament_champions_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_tournament_champions_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournament_entries",
                schema: "historical",
                columns: table => new
                {
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    entries = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tournament_entries", x => x.tournament_id);
                    table.ForeignKey(
                        name: "fk_tournament_entries_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournament_oil_patterns",
                schema: "app",
                columns: table => new
                {
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    oil_pattern_id = table.Column<string>(type: "character(26)", nullable: false),
                    tournament_rounds = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tournament_oil_patterns", x => new { x.tournament_id, x.oil_pattern_id });
                    table.ForeignKey(
                        name: "fk_tournament_oil_patterns_oil_patterns_oil_pattern_id",
                        column: x => x.oil_pattern_id,
                        principalSchema: "app",
                        principalTable: "oil_patterns",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_tournament_oil_patterns_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournament_results",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    place = table.Column<int>(type: "integer", nullable: false),
                    points = table.Column<int>(type: "integer", nullable: false),
                    prize_money = table.Column<decimal>(type: "numeric(6,2)", precision: 6, scale: 2, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_app_tournament_results", x => x.id);
                    table.UniqueConstraint("ak_app_tournament_results_domain_id", x => x.domain_id);
                    table.UniqueConstraint("ak_app_tournament_results_tournament_id_bowler_id", x => new { x.tournament_id, x.bowler_id });
                    table.ForeignKey(
                        name: "fk_tournament_results_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_tournament_results_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournament_results",
                schema: "historical",
                columns: table => new
                {
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    bowler_id = table.Column<int>(type: "integer", nullable: false),
                    side_cut_id = table.Column<int>(type: "integer", nullable: true),
                    place = table.Column<int>(type: "integer", nullable: true),
                    points = table.Column<int>(type: "integer", nullable: false),
                    prize_money = table.Column<decimal>(type: "numeric(6,2)", precision: 6, scale: 2, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_historical_tournament_results", x => new { x.tournament_id, x.bowler_id });
                    table.ForeignKey(
                        name: "fk_tournament_results_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_tournament_results_side_cuts_side_cut_id",
                        column: x => x.side_cut_id,
                        principalSchema: "app",
                        principalTable: "side_cuts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "fk_tournament_results_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tournament_sponsors",
                schema: "app",
                columns: table => new
                {
                    tournament_id = table.Column<int>(type: "integer", nullable: false),
                    sponsor_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    is_title_sponsor = table.Column<bool>(type: "boolean", nullable: false),
                    sponsorship_amount = table.Column<decimal>(type: "numeric(7,2)", precision: 7, scale: 2, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tournament_sponsors", x => new { x.tournament_id, x.sponsor_id });
                    table.ForeignKey(
                        name: "fk_tournament_sponsors_sponsors_sponsor_id",
                        column: x => x.sponsor_id,
                        principalSchema: "app",
                        principalTable: "sponsors",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_tournament_sponsors_tournaments_tournament_id",
                        column: x => x.tournament_id,
                        principalSchema: "app",
                        principalTable: "tournaments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "side_cut_criteria",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    side_cut_criteria_group_id = table.Column<int>(type: "integer", nullable: false),
                    minimum_age = table.Column<int>(type: "integer", nullable: true),
                    maximum_age = table.Column<int>(type: "integer", nullable: true),
                    gender_requirement = table.Column<string>(type: "character varying(1)", maxLength: 1, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_side_cut_criteria", x => x.id);
                    table.ForeignKey(
                        name: "fk_side_cut_criteria_side_cut_criteria_groups_side_cut_criteri",
                        column: x => x.side_cut_criteria_group_id,
                        principalSchema: "app",
                        principalTable: "side_cut_criteria_groups",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "article_attachments",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    article_id = table.Column<int>(type: "integer", nullable: false),
                    display_name = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    is_inline = table.Column<bool>(type: "boolean", nullable: false),
                    file_container = table.Column<string>(type: "character varying(63)", maxLength: 63, nullable: false),
                    file_path = table.Column<string>(type: "character varying(1023)", maxLength: 1023, nullable: false),
                    file_content_type = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    file_size_in_bytes = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_article_attachments", x => x.id);
                    table.ForeignKey(
                        name: "fk_article_attachments_articles_article_id",
                        column: x => x.article_id,
                        principalSchema: "app",
                        principalTable: "articles",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "squad_scores",
                schema: "app",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    domain_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    squad_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    bowler_id = table.Column<string>(type: "character(26)", fixedLength: true, maxLength: 26, nullable: false),
                    game_number = table.Column<short>(type: "smallint", nullable: false),
                    score = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_squad_scores", x => x.id);
                    table.UniqueConstraint("ak_squad_scores_domain_id", x => x.domain_id);
                    table.UniqueConstraint("ak_squad_scores_squad_id_bowler_id_game_number", x => new { x.squad_id, x.bowler_id, x.game_number });
                    table.ForeignKey(
                        name: "fk_squad_scores_bowlers_bowler_id",
                        column: x => x.bowler_id,
                        principalSchema: "app",
                        principalTable: "bowlers",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_squad_scores_squads_squad_id",
                        column: x => x.squad_id,
                        principalSchema: "app",
                        principalTable: "squads",
                        principalColumn: "domain_id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_article_attachments_article_id",
                schema: "app",
                table: "article_attachments",
                column: "article_id");

            migrationBuilder.CreateIndex(
                name: "ix_article_attachments_domain_id",
                schema: "app",
                table: "article_attachments",
                column: "domain_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_articles_publication_status_publish_date_utc",
                schema: "app",
                table: "articles",
                columns: new[] { "publication_status", "publish_date_utc" });

            migrationBuilder.CreateIndex(
                name: "ix_articles_slug",
                schema: "app",
                table: "articles",
                column: "slug",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_articles_tournament_id",
                schema: "app",
                table: "articles",
                column: "tournament_id");

            migrationBuilder.CreateIndex(
                name: "ix_bowler_of_the_year_awards_bowler_id",
                schema: "app",
                table: "bowler_of_the_year_awards",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_bowler_of_the_year_awards_season_id",
                schema: "app",
                table: "bowler_of_the_year_awards",
                column: "season_id");

            migrationBuilder.CreateIndex(
                name: "ix_bowler_season_stats_bowler_id",
                schema: "app",
                table: "bowler_season_stats",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_legacy_id",
                schema: "app",
                table: "bowlers",
                column: "legacy_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_name_last_name_name_first_name",
                schema: "app",
                table: "bowlers",
                columns: new[] { "last_name", "first_name" });

            migrationBuilder.CreateIndex(
                name: "ix_bowlers_website_id",
                schema: "app",
                table: "bowlers",
                column: "website_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_bowling_centers_legacy_id",
                schema: "app",
                table: "bowling_centers",
                column: "legacy_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_bowling_centers_website_id",
                schema: "app",
                table: "bowling_centers",
                column: "website_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_hall_of_fame_inductions_bowler_id",
                schema: "app",
                table: "hall_of_fame_inductions",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_hall_of_fame_inductions_induction_year",
                schema: "app",
                table: "hall_of_fame_inductions",
                column: "induction_year");

            migrationBuilder.CreateIndex(
                name: "ix_high_average_awards_bowler_id",
                schema: "app",
                table: "high_average_awards",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_high_average_awards_season_id",
                schema: "app",
                table: "high_average_awards",
                column: "season_id");

            migrationBuilder.CreateIndex(
                name: "ix_high_block_awards_bowler_id",
                schema: "app",
                table: "high_block_awards",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_high_block_awards_season_id",
                schema: "app",
                table: "high_block_awards",
                column: "season_id");

            migrationBuilder.CreateIndex(
                name: "ix_oil_patterns_kegel_id",
                schema: "app",
                table: "oil_patterns",
                column: "kegel_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_pending_uploads_container_path",
                schema: "staging",
                table: "pending_uploads",
                columns: new[] { "container", "path" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_side_cut_criteria_side_cut_criteria_group_id",
                schema: "app",
                table: "side_cut_criteria",
                column: "side_cut_criteria_group_id");

            migrationBuilder.CreateIndex(
                name: "ix_side_cut_criteria_groups_side_cut_id_sort_order",
                schema: "app",
                table: "side_cut_criteria_groups",
                columns: new[] { "side_cut_id", "sort_order" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_squad_scores_bowler_id",
                schema: "app",
                table: "squad_scores",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_squads_legacy_id",
                schema: "app",
                table: "squads",
                column: "legacy_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_squads_tournament_id",
                schema: "app",
                table: "squads",
                column: "tournament_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournament_champions_bowler_id",
                schema: "historical",
                table: "tournament_champions",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournament_oil_patterns_oil_pattern_id",
                schema: "app",
                table: "tournament_oil_patterns",
                column: "oil_pattern_id");

            migrationBuilder.CreateIndex(
                name: "ix_app_tournament_results_bowler_id",
                schema: "app",
                table: "tournament_results",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_historical_tournament_results_bowler_id",
                schema: "historical",
                table: "tournament_results",
                column: "bowler_id");

            migrationBuilder.CreateIndex(
                name: "ix_historical_tournament_results_side_cut_id",
                schema: "historical",
                table: "tournament_results",
                column: "side_cut_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournament_sponsors_sponsor_id",
                schema: "app",
                table: "tournament_sponsors",
                column: "sponsor_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournaments_bowling_center_id",
                schema: "app",
                table: "tournaments",
                column: "bowling_center_id");

            migrationBuilder.CreateIndex(
                name: "ix_tournaments_legacy_id",
                schema: "app",
                table: "tournaments",
                column: "legacy_id",
                unique: true)
                .Annotation("Npgsql:NullsDistinct", true);

            migrationBuilder.CreateIndex(
                name: "ix_tournaments_season_id",
                schema: "app",
                table: "tournaments",
                column: "season_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "article_attachments",
                schema: "app");

            migrationBuilder.DropTable(
                name: "bowler_of_the_year_awards",
                schema: "app");

            migrationBuilder.DropTable(
                name: "bowler_season_stats",
                schema: "app");

            migrationBuilder.DropTable(
                name: "bowling_center_lanes",
                schema: "app");

            migrationBuilder.DropTable(
                name: "bowling_center_phone_numbers",
                schema: "app");

            migrationBuilder.DropTable(
                name: "hall_of_fame_inductions",
                schema: "app");

            migrationBuilder.DropTable(
                name: "high_average_awards",
                schema: "app");

            migrationBuilder.DropTable(
                name: "high_block_awards",
                schema: "app");

            migrationBuilder.DropTable(
                name: "pending_uploads",
                schema: "staging");

            migrationBuilder.DropTable(
                name: "side_cut_criteria",
                schema: "app");

            migrationBuilder.DropTable(
                name: "sponsor_phone_numbers",
                schema: "app");

            migrationBuilder.DropTable(
                name: "squad_scores",
                schema: "app");

            migrationBuilder.DropTable(
                name: "tournament_champions",
                schema: "historical");

            migrationBuilder.DropTable(
                name: "tournament_entries",
                schema: "historical");

            migrationBuilder.DropTable(
                name: "tournament_oil_patterns",
                schema: "app");

            migrationBuilder.DropTable(
                name: "tournament_results",
                schema: "app");

            migrationBuilder.DropTable(
                name: "tournament_results",
                schema: "historical");

            migrationBuilder.DropTable(
                name: "tournament_sponsors",
                schema: "app");

            migrationBuilder.DropTable(
                name: "articles",
                schema: "app");

            migrationBuilder.DropTable(
                name: "side_cut_criteria_groups",
                schema: "app");

            migrationBuilder.DropTable(
                name: "squads",
                schema: "app");

            migrationBuilder.DropTable(
                name: "oil_patterns",
                schema: "app");

            migrationBuilder.DropTable(
                name: "bowlers",
                schema: "app");

            migrationBuilder.DropTable(
                name: "sponsors",
                schema: "app");

            migrationBuilder.DropTable(
                name: "side_cuts",
                schema: "app");

            migrationBuilder.DropTable(
                name: "tournaments",
                schema: "app");

            migrationBuilder.DropTable(
                name: "bowling_centers",
                schema: "app");

            migrationBuilder.DropTable(
                name: "seasons",
                schema: "app");
        }
    }
}
