// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neba.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Neba.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.HasKey("db_id")
                        .HasName("pk_bowlers");

                    b.HasAlternateKey("Id")
                        .HasName("ak_bowlers_domain_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowlers_legacy_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("LegacyId"), true);

                    b.HasIndex("WebsiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowlers_website_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("WebsiteId"), true);

                    b.ToTable("bowlers", "app");
                });

            modelBuilder.Entity("Neba.Domain.BowlingCenters.BowlingCenter", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("certification_number");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.Property<int?>("WebsiteId")
                        .HasColumnType("integer")
                        .HasColumnName("website_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Neba.Domain.BowlingCenters.BowlingCenter.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("country")
                                .IsFixedLength();

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("state")
                                .IsFixedLength();

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");

                            b1.Property<string>("Unit")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Coordinates", "Neba.Domain.BowlingCenters.BowlingCenter.Address#Address.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmailAddress", "Neba.Domain.BowlingCenters.BowlingCenter.EmailAddress#EmailAddress", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email_address");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_bowling_centers");

                    b.HasAlternateKey("CertificationNumber")
                        .HasName("ak_bowling_centers_certification_number");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowling_centers_legacy_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("LegacyId"), true);

                    b.HasIndex("WebsiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_bowling_centers_website_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("WebsiteId"), true);

                    b.ToTable("bowling_centers", "app");
                });

            modelBuilder.Entity("Neba.Domain.HallOfFame.HallOfFameInduction", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("BowlerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("bowler_id")
                        .IsFixedLength();

                    b.Property<int>("Categories")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("induction_year");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Photo", "Neba.Domain.HallOfFame.HallOfFameInduction.Photo#StoredFile", b1 =>
                        {
                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("character varying(63)")
                                .HasColumnName("photo_container");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("photo_content_type");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(1023)
                                .HasColumnType("character varying(1023)")
                                .HasColumnName("photo_file_path");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("photo_size_in_bytes");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_hall_of_fame_inductions");

                    b.HasAlternateKey("Id")
                        .HasName("ak_hall_of_fame_inductions_domain_id");

                    b.HasAlternateKey("Year", "BowlerId")
                        .HasName("ak_hall_of_fame_inductions_induction_year_bowler_id");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_hall_of_fame_inductions_bowler_id");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_hall_of_fame_inductions_induction_year");

                    b.ToTable("hall_of_fame_inductions", "app");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.BowlerOfTheYearAward", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("BowlerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("bowler_id")
                        .IsFixedLength();

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int>("season_id")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("db_id")
                        .HasName("pk_bowler_of_the_year_awards");

                    b.HasAlternateKey("Id")
                        .HasName("ak_bowler_of_the_year_awards_domain_id");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_bowler_of_the_year_awards_bowler_id");

                    b.HasIndex("season_id")
                        .HasDatabaseName("ix_bowler_of_the_year_awards_season_id");

                    b.ToTable("bowler_of_the_year_awards", "app");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.HighAverageAward", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<decimal>("Average")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("average");

                    b.Property<string>("BowlerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("bowler_id")
                        .IsFixedLength();

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int?>("TotalGames")
                        .HasColumnType("integer")
                        .HasColumnName("total_games");

                    b.Property<int?>("TournamentsParticipated")
                        .HasColumnType("integer")
                        .HasColumnName("tournaments_participated");

                    b.Property<int>("season_id")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("db_id")
                        .HasName("pk_high_average_awards");

                    b.HasAlternateKey("Id")
                        .HasName("ak_high_average_awards_domain_id");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_high_average_awards_bowler_id");

                    b.HasIndex("season_id")
                        .HasDatabaseName("ix_high_average_awards_season_id");

                    b.ToTable("high_average_awards", "app");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.HighBlockAward", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<int>("BlockScore")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("BowlerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("bowler_id")
                        .IsFixedLength();

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int>("season_id")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("db_id")
                        .HasName("pk_high_block_awards");

                    b.HasAlternateKey("Id")
                        .HasName("ak_high_block_awards_domain_id");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_high_block_awards_bowler_id");

                    b.HasIndex("season_id")
                        .HasDatabaseName("ix_high_block_awards_season_id");

                    b.ToTable("high_block_awards", "app");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.Season", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("db_id")
                        .HasName("pk_seasons");

                    b.HasAlternateKey("Id")
                        .HasName("ak_seasons_domain_id");

                    b.ToTable("seasons", "app");
                });

            modelBuilder.Entity("Neba.Domain.Sponsors.Sponsor", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)")
                        .HasColumnName("description");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("facebook_url");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("instagram_url");

                    b.Property<bool>("IsCurrentSponsor")
                        .HasColumnType("boolean")
                        .HasColumnName("current_sponsor");

                    b.Property<string>("LiveReadText")
                        .HasMaxLength(2047)
                        .HasColumnType("character varying(2047)")
                        .HasColumnName("live_read_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("PromotionalNotes")
                        .HasMaxLength(4095)
                        .HasColumnType("character varying(4095)")
                        .HasColumnName("promotional_notes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("TagPhrase")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tag_phrase");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website_url");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BusinessAddress", "Neba.Domain.Sponsors.Sponsor.BusinessAddress#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("business_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("business_country")
                                .IsFixedLength();

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("business_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character(2)")
                                .HasColumnName("business_region")
                                .IsFixedLength();

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("business_street");

                            b1.Property<string>("Unit")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("business_unit");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Coordinates", "Neba.Domain.Sponsors.Sponsor.BusinessAddress#Address.Coordinates#Coordinates", b2 =>
                                {
                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("business_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("business_longitude");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BusinessEmail", "Neba.Domain.Sponsors.Sponsor.BusinessEmail#EmailAddress", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("business_email_address");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Logo", "Neba.Domain.Sponsors.Sponsor.Logo#StoredFile", b1 =>
                        {
                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("character varying(63)")
                                .HasColumnName("logo_container_name");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("logo_content_type");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(1023)
                                .HasColumnType("character varying(1023)")
                                .HasColumnName("logo_file_path");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("logo_size_in_bytes");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_sponsors");

                    b.HasAlternateKey("Id")
                        .HasName("ak_sponsors_domain_id");

                    b.HasAlternateKey("Slug")
                        .HasName("ak_sponsors_slug");

                    b.ToTable("sponsors", "app");
                });

            modelBuilder.Entity("Neba.Domain.Stats.BowlerSeasonStats", b =>
                {
                    b.Property<string>("SeasonId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("season_id")
                        .IsFixedLength();

                    b.Property<string>("BowlerId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("bowler_id")
                        .IsFixedLength();

                    b.Property<decimal?>("AverageFinish")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("average_finish");

                    b.Property<int>("BowlerOfTheYearPoints")
                        .HasColumnType("integer")
                        .HasColumnName("bowler_of_the_year_points");

                    b.Property<int>("Cashes")
                        .HasColumnType("integer")
                        .HasColumnName("cashes");

                    b.Property<decimal>("Credits")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("credits");

                    b.Property<decimal>("CupEarnings")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("cup_earnings");

                    b.Property<int>("EligibleEntries")
                        .HasColumnType("integer")
                        .HasColumnName("entries");

                    b.Property<int>("EligibleTournaments")
                        .HasColumnType("integer")
                        .HasColumnName("tournaments");

                    b.Property<decimal>("FieldAverage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("field_average");

                    b.Property<int>("Finals")
                        .HasColumnType("integer")
                        .HasColumnName("finals");

                    b.Property<int>("HighBlock")
                        .HasColumnType("integer")
                        .HasColumnName("high_block");

                    b.Property<int?>("HighFinish")
                        .HasColumnType("integer")
                        .HasColumnName("high_finish");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean")
                        .HasColumnName("is_member");

                    b.Property<bool>("IsRookie")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rookie");

                    b.Property<bool>("IsSenior")
                        .HasColumnType("boolean")
                        .HasColumnName("is_senior");

                    b.Property<bool>("IsSuperSenior")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_senior");

                    b.Property<bool>("IsWoman")
                        .HasColumnType("boolean")
                        .HasColumnName("is_woman");

                    b.Property<bool>("IsYouth")
                        .HasColumnType("boolean")
                        .HasColumnName("is_youth");

                    b.Property<DateTimeOffset>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_utc");

                    b.Property<int>("MatchPlayGames")
                        .HasColumnType("integer")
                        .HasColumnName("match_play_games");

                    b.Property<int>("MatchPlayHighGame")
                        .HasColumnType("integer")
                        .HasColumnName("match_play_high_game");

                    b.Property<int>("MatchPlayLosses")
                        .HasColumnType("integer")
                        .HasColumnName("match_play_losses");

                    b.Property<int>("MatchPlayPinfall")
                        .HasColumnType("integer")
                        .HasColumnName("match_play_pinfall");

                    b.Property<int>("MatchPlayWins")
                        .HasColumnType("integer")
                        .HasColumnName("match_play_wins");

                    b.Property<int>("QualifyingHighGame")
                        .HasColumnType("integer")
                        .HasColumnName("qualifying_high_game");

                    b.Property<int>("SeniorOfTheYearPoints")
                        .HasColumnType("integer")
                        .HasColumnName("senior_of_the_year_points");

                    b.Property<int>("SuperSeniorOfTheYearPoints")
                        .HasColumnType("integer")
                        .HasColumnName("super_senior_of_the_year_points");

                    b.Property<int>("TotalEntries")
                        .HasColumnType("integer")
                        .HasColumnName("total_entries");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer")
                        .HasColumnName("total_games");

                    b.Property<int>("TotalPinfall")
                        .HasColumnType("integer")
                        .HasColumnName("total_pinfall");

                    b.Property<int>("TotalTournaments")
                        .HasColumnType("integer")
                        .HasColumnName("total_tournaments");

                    b.Property<decimal>("TournamentWinnings")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("tournament_winnings");

                    b.Property<int>("WomanOfTheYearPoints")
                        .HasColumnType("integer")
                        .HasColumnName("woman_of_the_year_points");

                    b.Property<int>("YouthOfTheYearPoints")
                        .HasColumnType("integer")
                        .HasColumnName("youth_of_the_year_points");

                    b.HasKey("SeasonId", "BowlerId")
                        .HasName("pk_bowler_season_stats");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_bowler_season_stats_bowler_id");

                    b.ToTable("bowler_season_stats", "app");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.OilPattern", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<Guid?>("KegelId")
                        .HasColumnType("uuid")
                        .HasColumnName("kegel_id");

                    b.Property<decimal>("LeftRatio")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("left_ratio");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("name");

                    b.Property<decimal>("RightRatio")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("right_ratio");

                    b.Property<decimal>("Volume")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("volume");

                    b.HasKey("db_id")
                        .HasName("pk_oil_patterns");

                    b.HasAlternateKey("Id")
                        .HasName("ak_oil_patterns_domain_id");

                    b.HasIndex("KegelId")
                        .IsUnique()
                        .HasDatabaseName("ix_oil_patterns_kegel_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("KegelId"), true);

                    b.ToTable("oil_patterns", "app");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.SideCut", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int>("Indicator")
                        .HasColumnType("integer")
                        .HasColumnName("color_indicator");

                    b.Property<string>("LogicalOperator")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("logical_operator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)")
                        .HasColumnName("name");

                    b.HasKey("db_id")
                        .HasName("pk_side_cuts");

                    b.HasAlternateKey("Id")
                        .HasName("ak_side_cuts_domain_id");

                    b.ToTable("side_cuts", "app");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.SideCutCriteria", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("GenderRequirement")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gender_requirement");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_age");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_age");

                    b.Property<int>("side_cut_criteria_group_id")
                        .HasColumnType("integer")
                        .HasColumnName("side_cut_criteria_group_id");

                    b.HasKey("db_id")
                        .HasName("pk_side_cut_criteria");

                    b.HasIndex("side_cut_criteria_group_id")
                        .HasDatabaseName("ix_side_cut_criteria_side_cut_criteria_group_id");

                    b.ToTable("side_cut_criteria", "app");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.SideCutCriteriaGroup", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<string>("LogicalOperator")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("logical_operator");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("side_cut_id")
                        .HasColumnType("integer")
                        .HasColumnName("side_cut_id");

                    b.HasKey("db_id")
                        .HasName("pk_side_cut_criteria_groups");

                    b.HasAlternateKey("Id")
                        .HasName("ak_side_cut_criteria_groups_domain_id");

                    b.HasIndex("side_cut_id", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_side_cut_criteria_groups_side_cut_id_sort_order");

                    b.ToTable("side_cut_criteria_groups", "app");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<int>("db_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("db_id"));

                    b.Property<string>("BowlingCenterId")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("bowling_center_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal>("EntryFee")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("entry_fee");

                    b.Property<string>("ExternalRegistrationUrl")
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)")
                        .HasColumnName("external_registration_url");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("domain_id")
                        .IsFixedLength();

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("name");

                    b.Property<int?>("PatternLengthCategory")
                        .HasColumnType("integer")
                        .HasColumnName("pattern_length_category");

                    b.Property<int?>("PatternRatioCategory")
                        .HasColumnType("integer")
                        .HasColumnName("pattern_ratio_category");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("season_id")
                        .IsFixedLength();

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<bool>("StatsEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("stats_eligible");

                    b.Property<int>("TournamentType")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_type");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Logo", "Neba.Domain.Tournaments.Tournament.Logo#StoredFile", b1 =>
                        {
                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("character varying(63)")
                                .HasColumnName("logo_container");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("logo_content_type");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasMaxLength(1023)
                                .HasColumnType("character varying(1023)")
                                .HasColumnName("logo_file_path");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("logo_size_in_bytes");
                        });

                    b.HasKey("db_id")
                        .HasName("pk_tournaments");

                    b.HasAlternateKey("Id")
                        .HasName("ak_tournaments_domain_id");

                    b.HasIndex("BowlingCenterId")
                        .HasDatabaseName("ix_tournaments_bowling_center_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ix_tournaments_legacy_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("LegacyId"), true);

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_tournaments_season_id");

                    b.ToTable("tournaments", "app");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.TournamentOilPattern", b =>
                {
                    b.Property<int>("tournament_id")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<string>("OilPatternId")
                        .HasColumnType("character(26)")
                        .HasColumnName("oil_pattern_id");

                    b.Property<int>("TournamentRounds")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_rounds");

                    b.HasKey("tournament_id", "OilPatternId")
                        .HasName("pk_tournament_oil_patterns");

                    b.HasIndex("OilPatternId")
                        .HasDatabaseName("ix_tournament_oil_patterns_oil_pattern_id");

                    b.ToTable("tournament_oil_patterns", "app");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.TournamentSponsor", b =>
                {
                    b.Property<int>("tournament_id")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<string>("SponsorId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)")
                        .HasColumnName("sponsor_id")
                        .IsFixedLength();

                    b.Property<decimal>("SponsorshipAmount")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("sponsorship_amount");

                    b.Property<bool>("TitleSponsor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_title_sponsor");

                    b.HasKey("tournament_id", "SponsorId")
                        .HasName("pk_tournament_sponsors");

                    b.HasIndex("SponsorId")
                        .HasDatabaseName("ix_tournament_sponsors_sponsor_id");

                    b.ToTable("tournament_sponsors", "app");
                });

            modelBuilder.Entity("Neba.Infrastructure.Database.Entities.HistoricalTournamentChampion", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<int>("BowlerId")
                        .HasColumnType("integer")
                        .HasColumnName("bowler_id");

                    b.HasKey("TournamentId", "BowlerId")
                        .HasName("pk_tournament_champions");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_tournament_champions_bowler_id");

                    b.ToTable("tournament_champions", "historical");
                });

            modelBuilder.Entity("Neba.Infrastructure.Database.Entities.HistoricalTournamentEntry", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<int>("Entries")
                        .HasColumnType("integer")
                        .HasColumnName("entries");

                    b.HasKey("TournamentId")
                        .HasName("pk_tournament_entries");

                    b.ToTable("tournament_entries", "historical");
                });

            modelBuilder.Entity("Neba.Infrastructure.Database.Entities.HistoricalTournamentResult", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<int>("BowlerId")
                        .HasColumnType("integer")
                        .HasColumnName("bowler_id");

                    b.Property<int?>("Place")
                        .HasColumnType("integer")
                        .HasColumnName("place");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<decimal>("PrizeMoney")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("prize_money");

                    b.Property<int?>("SideCutId")
                        .HasColumnType("integer")
                        .HasColumnName("side_cut_id");

                    b.HasKey("TournamentId", "BowlerId")
                        .HasName("pk_tournament_results");

                    b.HasIndex("BowlerId")
                        .HasDatabaseName("ix_tournament_results_bowler_id");

                    b.HasIndex("SideCutId")
                        .HasDatabaseName("ix_tournament_results_side_cut_id");

                    b.ToTable("tournament_results", "historical");
                });

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.OwnsOne("Neba.Domain.Bowlers.Name", "Name", b1 =>
                        {
                            b1.Property<int>("Bowlerdb_id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(31)
                                .HasColumnType("character varying(31)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("character varying(63)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(31)
                                .HasColumnType("character varying(31)")
                                .HasColumnName("middle_name");

                            b1.Property<string>("Nickname")
                                .HasMaxLength(31)
                                .HasColumnType("character varying(31)")
                                .HasColumnName("nickname");

                            b1.Property<string>("Suffix")
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("suffix");

                            b1.HasKey("Bowlerdb_id");

                            b1.HasIndex("LastName", "FirstName")
                                .HasDatabaseName("ix_bowlers_name_last_name_name_first_name");

                            b1.ToTable("bowlers", "app");

                            b1.WithOwner()
                                .HasForeignKey("Bowlerdb_id")
                                .HasConstraintName("fk_bowlers_bowlers_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Neba.Domain.BowlingCenters.BowlingCenter", b =>
                {
                    b.OwnsOne("Neba.Domain.BowlingCenters.LaneConfiguration", "Lanes", b1 =>
                        {
                            b1.Property<int>("BowlingCenterdb_id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.HasKey("BowlingCenterdb_id");

                            b1.ToTable("bowling_centers", "app");

                            b1.WithOwner()
                                .HasForeignKey("BowlingCenterdb_id")
                                .HasConstraintName("fk_bowling_centers_bowling_centers_id");

                            b1.OwnsMany("Neba.Domain.BowlingCenters.LaneRange", "Ranges", b2 =>
                                {
                                    b2.Property<int>("bowling_center_id")
                                        .HasColumnType("integer")
                                        .HasColumnName("bowling_center_id");

                                    b2.Property<int>("StartLane")
                                        .HasColumnType("integer")
                                        .HasColumnName("start_lane");

                                    b2.Property<int>("EndLane")
                                        .HasColumnType("integer")
                                        .HasColumnName("end_lane");

                                    b2.Property<string>("PinFallType")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character(2)")
                                        .HasColumnName("pin_fall_type")
                                        .IsFixedLength();

                                    b2.HasKey("bowling_center_id", "StartLane")
                                        .HasName("pk_bowling_center_lanes");

                                    b2.ToTable("bowling_center_lanes", "app");

                                    b2.WithOwner()
                                        .HasForeignKey("bowling_center_id")
                                        .HasConstraintName("fk_bowling_center_lanes_bowling_centers_bowling_center_id");
                                });

                            b1.Navigation("Ranges");
                        });

                    b.OwnsMany("Neba.Domain.Contact.PhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<int>("bowling_center_id")
                                .HasColumnType("integer")
                                .HasColumnName("bowling_center_id");

                            b1.Property<string>("Type")
                                .HasMaxLength(1)
                                .HasColumnType("character(1)")
                                .HasColumnName("phone_type")
                                .IsFixedLength();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("phone_country_code");

                            b1.Property<string>("Extension")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_extension");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("bowling_center_id", "Type")
                                .HasName("pk_bowling_center_phone_numbers");

                            b1.ToTable("bowling_center_phone_numbers", "app");

                            b1.WithOwner()
                                .HasForeignKey("bowling_center_id")
                                .HasConstraintName("fk_bowling_center_phone_numbers_bowling_centers_bowling_center");
                        });

                    b.Navigation("Lanes")
                        .IsRequired();

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("Neba.Domain.HallOfFame.HallOfFameInduction", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hall_of_fame_inductions_bowlers_bowler_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.BowlerOfTheYearAward", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bowler_of_the_year_awards_bowlers_bowler_id");

                    b.HasOne("Neba.Domain.Seasons.Season", null)
                        .WithMany("BowlerOfTheYearAwards")
                        .HasForeignKey("season_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bowler_of_the_year_awards_seasons_season_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.HighAverageAward", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_high_average_awards_bowlers_bowler_id");

                    b.HasOne("Neba.Domain.Seasons.Season", null)
                        .WithMany("HighAverageAwards")
                        .HasForeignKey("season_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_high_average_awards_seasons_season_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.HighBlockAward", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_high_block_awards_bowlers_bowler_id");

                    b.HasOne("Neba.Domain.Seasons.Season", null)
                        .WithMany("HighBlockAwards")
                        .HasForeignKey("season_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_high_block_awards_seasons_season_id");

                    b.Navigation("Bowler");
                });

            modelBuilder.Entity("Neba.Domain.Sponsors.Sponsor", b =>
                {
                    b.OwnsOne("Neba.Domain.Sponsors.ContactInfo", "SponsorContact", b1 =>
                        {
                            b1.Property<int>("Sponsordb_id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(127)
                                .HasColumnType("character varying(127)")
                                .HasColumnName("contact_name");

                            b1.HasKey("Sponsordb_id");

                            b1.ToTable("sponsors", "app");

                            b1.WithOwner()
                                .HasForeignKey("Sponsordb_id")
                                .HasConstraintName("fk_sponsors_sponsors_id");

                            b1.OwnsOne("Neba.Domain.Contact.EmailAddress", "Email", b2 =>
                                {
                                    b2.Property<int>("ContactInfoSponsordb_id")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("contact_email_address");

                                    b2.HasKey("ContactInfoSponsordb_id");

                                    b2.ToTable("sponsors", "app");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoSponsordb_id")
                                        .HasConstraintName("fk_sponsors_sponsors_id");
                                });

                            b1.OwnsOne("Neba.Domain.Contact.PhoneNumber", "Phone", b2 =>
                                {
                                    b2.Property<int>("ContactInfoSponsordb_id")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<string>("CountryCode")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("contact_phone_country_code");

                                    b2.Property<string>("Extension")
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("contact_phone_extension");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(15)
                                        .HasColumnType("character varying(15)")
                                        .HasColumnName("contact_phone_number");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(1)
                                        .HasColumnType("character(1)")
                                        .HasColumnName("contact_phone_type")
                                        .IsFixedLength();

                                    b2.HasKey("ContactInfoSponsordb_id");

                                    b2.ToTable("sponsors", "app");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoSponsordb_id")
                                        .HasConstraintName("fk_sponsors_sponsors_id");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("Phone")
                                .IsRequired();
                        });

                    b.OwnsMany("Neba.Domain.Contact.PhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<int>("sponsor_id")
                                .HasColumnType("integer")
                                .HasColumnName("sponsor_id");

                            b1.Property<string>("Type")
                                .HasMaxLength(1)
                                .HasColumnType("character(1)")
                                .HasColumnName("phone_type")
                                .IsFixedLength();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("phone_country_code");

                            b1.Property<string>("Extension")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phone_extension");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("phone_number");

                            b1.HasKey("sponsor_id", "Type")
                                .HasName("pk_sponsor_phone_numbers");

                            b1.ToTable("sponsor_phone_numbers", "app");

                            b1.WithOwner()
                                .HasForeignKey("sponsor_id")
                                .HasConstraintName("fk_sponsor_phone_numbers_sponsors_sponsor_id");
                        });

                    b.Navigation("PhoneNumbers");

                    b.Navigation("SponsorContact");
                });

            modelBuilder.Entity("Neba.Domain.Stats.BowlerSeasonStats", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany("SeasonStats")
                        .HasForeignKey("BowlerId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bowler_season_stats_bowlers_bowler_id");

                    b.HasOne("Neba.Domain.Seasons.Season", "Season")
                        .WithMany("BowlerStats")
                        .HasForeignKey("SeasonId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bowler_season_stats_seasons_season_id");

                    b.Navigation("Bowler");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.SideCutCriteria", b =>
                {
                    b.HasOne("Neba.Domain.Tournaments.SideCutCriteriaGroup", "CriteriaGroup")
                        .WithMany("Criteria")
                        .HasForeignKey("side_cut_criteria_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_side_cut_criteria_side_cut_criteria_groups_side_cut_criteri");

                    b.Navigation("CriteriaGroup");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.SideCutCriteriaGroup", b =>
                {
                    b.HasOne("Neba.Domain.Tournaments.SideCut", "SideCut")
                        .WithMany("CriteriaGroups")
                        .HasForeignKey("side_cut_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_side_cut_criteria_groups_side_cuts_side_cut_id");

                    b.Navigation("SideCut");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.Tournament", b =>
                {
                    b.HasOne("Neba.Domain.BowlingCenters.BowlingCenter", "BowlingCenter")
                        .WithMany()
                        .HasForeignKey("BowlingCenterId")
                        .HasPrincipalKey("CertificationNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_tournaments_bowling_centers_bowling_center_id");

                    b.HasOne("Neba.Domain.Seasons.Season", "Season")
                        .WithMany("Tournaments")
                        .HasForeignKey("SeasonId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tournaments_seasons_season_id");

                    b.Navigation("BowlingCenter");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.TournamentOilPattern", b =>
                {
                    b.HasOne("Neba.Domain.Tournaments.OilPattern", "OilPattern")
                        .WithMany("Tournaments")
                        .HasForeignKey("OilPatternId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_oil_patterns_oil_patterns_oil_pattern_id");

                    b.HasOne("Neba.Domain.Tournaments.Tournament", "Tournament")
                        .WithMany("OilPatterns")
                        .HasForeignKey("tournament_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_oil_patterns_tournaments_tournament_id");

                    b.Navigation("OilPattern");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.TournamentSponsor", b =>
                {
                    b.HasOne("Neba.Domain.Sponsors.Sponsor", "Sponsor")
                        .WithMany("TournamentsSponsored")
                        .HasForeignKey("SponsorId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_sponsors_sponsors_sponsor_id");

                    b.HasOne("Neba.Domain.Tournaments.Tournament", "Tournament")
                        .WithMany("Sponsors")
                        .HasForeignKey("tournament_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_sponsors_tournaments_tournament_id");

                    b.Navigation("Sponsor");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Neba.Infrastructure.Database.Entities.HistoricalTournamentChampion", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_champions_bowlers_bowler_id");

                    b.HasOne("Neba.Domain.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_champions_tournaments_tournament_id");

                    b.Navigation("Bowler");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Neba.Infrastructure.Database.Entities.HistoricalTournamentEntry", b =>
                {
                    b.HasOne("Neba.Domain.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_entries_tournaments_tournament_id");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Neba.Infrastructure.Database.Entities.HistoricalTournamentResult", b =>
                {
                    b.HasOne("Neba.Domain.Bowlers.Bowler", "Bowler")
                        .WithMany()
                        .HasForeignKey("BowlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_results_bowlers_bowler_id");

                    b.HasOne("Neba.Domain.Tournaments.SideCut", "SideCut")
                        .WithMany()
                        .HasForeignKey("SideCutId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tournament_results_side_cuts_side_cut_id");

                    b.HasOne("Neba.Domain.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_results_tournaments_tournament_id");

                    b.Navigation("Bowler");

                    b.Navigation("SideCut");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Neba.Domain.Bowlers.Bowler", b =>
                {
                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("Neba.Domain.Seasons.Season", b =>
                {
                    b.Navigation("BowlerOfTheYearAwards");

                    b.Navigation("BowlerStats");

                    b.Navigation("HighAverageAwards");

                    b.Navigation("HighBlockAwards");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Neba.Domain.Sponsors.Sponsor", b =>
                {
                    b.Navigation("TournamentsSponsored");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.OilPattern", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.SideCut", b =>
                {
                    b.Navigation("CriteriaGroups");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.SideCutCriteriaGroup", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Neba.Domain.Tournaments.Tournament", b =>
                {
                    b.Navigation("OilPatterns");

                    b.Navigation("Sponsors");
                });
#pragma warning restore 612, 618
        }
    }
}
